# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w_FCLga2YFJLMOx5cxAX3EX_lzeKgD1i
"""

class car:
  def __init__(self,car_name,car_color):
    self.carname=car_name
    self.carcolor=car_color
  def engine(self,eng="1000"):
    print("car is {self.carname},color is {self.carcolor}has an engine{eng}")

a=car("tata","white")
a

a.engine()

class dressing:
  def __init__(self,dress_type,dress_color):
    self.typedress=dress_type
    self.colordress=dress_color
  def saree(self):
    print("dress is {self.typedress}, color of dress is {self.colordress},otherwiuse it is saree{self}")

A=dressing("one piecw","white")
A.saree()